<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Building Inspection Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        @page{

            size:A4 landscape;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>CvSU Carmona Campus</div>

<div>Carmona, Cavite</div>

<div>(046) 487-6328</div>

<div><a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a></div>

</td>

<td width="90">

<img
src="{{ asset('images/bagong-pilipinas.png') }}"
width="80">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">
    BUILDING INSPECTION REPORT
</h2>

<p class="text-center">
    @if($dateFrom || $dateTo)
        ({{ $dateFrom ?? 'earliest' }} to {{ $dateTo ?? 'latest' }})
    @endif
</p>

<table class="section">

<tr>
<td><strong>Generated Date</strong></td>
<td>{{ now()->format('F d, Y h:i A') }}</td>
<td><strong>Generated By</strong></td>
<td>{{ auth()->user()->fullname ?? auth()->user()->name }}</td>
</tr>

<tr>
<td><strong>Total Inspections</strong></td>
<td>{{ $totalInspections }}</td>
<td><strong>Good / Needs Attention / Critical</strong></td>
<td>{{ $goodCount }} / {{ $needsAttentionCount }} / {{ $criticalCount }}</td>
</tr>

</table>

<table class="section">

<thead>
<tr>
    <th>Reference No.</th>
    <th>Building</th>
    <th>In-Charge</th>
    <th>Inspection Date</th>
    <th>Inspected By</th>
    <th>Condition</th>
    <th>Issues Flagged</th>
</tr>
</thead>

<tbody>

@forelse($inspections as $inspection)

@php $score = $inspection->conditionScore(); @endphp

<tr>
<td>{{ $inspection->reference_no }}</td>
<td>{{ $inspection->building_name }}</td>
<td>{{ $inspection->building_in_charge ?? '-' }}</td>
<td class="text-center">{{ $inspection->inspection_date->format('M d, Y') }}</td>
<td>{{ $inspection->inspector->fullname ?? $inspection->inspector->name ?? '-' }}</td>
<td class="text-center">{{ $score['label'] }}</td>
<td class="text-center">{{ $score['flagged'] }} of {{ $score['total'] }}</td>
</tr>

@empty

<tr>
<td colspan="7" class="text-center">No inspections match these filters.</td>
</tr>

@endforelse

</tbody>

</table>

</body>

</html>
