@extends('layouts.app')

@section('content')

{{-- ===========================================
    SCREEN REPORT
=========================================== --}}
<div class="bg-white rounded-xl shadow-lg p-6 lg:p-8">

    {{-- ==========================================================
        OFFICIAL UNIVERSITY PRINT HEADER
    ========================================================== --}}

    <div class="hidden print:block mb-8">

        <table class="w-full">

            <tr>

                <td style="width:110px">

                    <img
                        src="{{ asset('images/logo.png') }}"
                        alt="CvSU Logo"
                        style="width:90px;height:90px;">

                </td>

                <td class="text-center">

                    <p class="text-sm">

                        Republic of the Philippines

                    </p>

                    <h2 class="text-2xl font-bold uppercase">

                        Cavite State University

                    </h2>

                    <p>

                        CvSU Carmona Campus

                    </p>

                    <p>

                        Carmona, Cavite

                    </p>

                    <p>

                        (046) 487-6328

                    </p>

                    <p>

                        <a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a>

                    </p>

                </td>

                <td style="width:110px">

                    <img
                        src="{{ asset('images/bagong-pilipinas.png') }}"
                        alt="Bagong Pilipinas"
                        style="width:90px;height:90px;">

                </td>

            </tr>

        </table>

        <hr class="border-2 border-black mt-4">

        <div class="text-center mt-5">

            <h2 class="text-2xl font-bold uppercase">

                @yield('report-title')

            </h2>

            <p class="mt-2">

                @yield('report-description')

            </p>

        </div>

    </div>


    {{-- =========================
        REPORT HEADER
        (h1 is intentionally kept — the print stylesheet below hides h1
        specifically so the printed page shows only the letterhead's title,
        not this one)
    ========================== --}}
    <div class="flex justify-between items-start mb-6">

        <div>

            <h1 class="text-3xl lg:text-4xl font-bold text-gray-800 flex items-center gap-3">

                @yield('report-title')

            </h1>

            <p class="text-gray-500 text-lg mt-1">

                @yield('report-description')

            </p>

            <div class="mt-6 border border-gray-200 rounded-xl p-5 bg-gray-50 print:bg-white print:text-black print:border-gray-400">

                <div class="grid grid-cols-2 gap-4 text-base text-gray-700">

                    <div>

                        <span class="font-semibold">
                            Report No.
                        </span>

                        <p class="mt-1">

                            {{ strtoupper(substr(trim($__env->yieldContent('report-title')),0,3)) }}-{{ now()->format('YmdHis') }}

                        </p>

                    </div>

                    <div>

                        <span class="font-semibold">
                            Office
                        </span>

                        <p class="mt-1">

                            General Services Office

                        </p>

                    </div>

                    <div>

                        <span class="font-semibold">
                            Generated Date
                        </span>

                        <p class="mt-1">

                            {{ now()->format('F d, Y h:i A') }}

                        </p>

                    </div>

                    <div>

                        <span class="font-semibold">
                            Generated By
                        </span>

                        <p class="mt-1">

                            {{ auth()->user()->fullname ?? auth()->user()->name }}

                        </p>

                    </div>

                </div>

            </div>

        </div>



        <div>

            <a
                href="{{ route(Route::currentRouteName().'.print') }}{{ request()->getQueryString() ? '?'.request()->getQueryString() : '' }}"
                target="_blank"
                class="bg-green-600 hover:bg-green-700 text-white px-5 py-3 rounded">

                🖨 Print Official Report

            </a>

        </div>

    </div>


    {{-- =========================
        KPI CARDS
    ========================== --}}

    @yield('kpi-cards')


    {{-- =========================
        EXECUTIVE SUMMARY
    ========================== --}}

    <div class="border border-blue-200 rounded-lg p-6 mb-6 bg-blue-50">

        <h3 class="text-xl font-bold text-blue-800 mb-4">

            Executive Assessment

        </h3>

        @yield('executive-summary')

    </div>


    {{-- =========================
        REPORT TABLE
    ========================== --}}

    <div class="border rounded-lg mb-6 overflow-hidden">

        <div class="border-b p-5 bg-gray-50">

            <h3 class="text-xl font-bold text-gray-800">

                @yield('table-title')

            </h3>

        </div>

        @yield('report-table')

    </div>


    {{-- =========================
        RECOMMENDATIONS
    ========================== --}}

    <div class="border border-yellow-300 rounded-lg p-6 mb-6 bg-yellow-50">

        <h3 class="text-xl font-bold text-yellow-800 mb-4">

            Recommendation

        </h3>

        @yield('recommendation')

    </div>


    {{-- =========================
        SIGNATURES
    ========================== --}}

    <div class="border rounded-lg p-8">

        <div class="grid grid-cols-3 gap-10 text-center">

            <div>

                <div class="border-b border-gray-500 h-12 mb-2"></div>

                <strong>Prepared By</strong>

                <p class="mt-2 text-sm text-gray-600">

                    {{ auth()->user()->fullname ?? auth()->user()->name }}

                </p>

            </div>

            <div>

                <div class="border-b border-gray-500 h-12 mb-2"></div>

                <strong>Reviewed By</strong>

            </div>

            <div>

                <div class="border-b border-gray-500 h-12 mb-2"></div>

                <strong>Approved By</strong>

            </div>

        </div>

    </div>

</div>

   

<style>

@media print{

    /* ==========================================
       PAGE SETUP
    ========================================== */

    @page{

        size:A4 portrait;
        margin:8mm;

    }

    html,
    body{

        background:#fff !important;
        color:#000 !important;
        font-size:11px !important;

    }

    /* ==========================================
       HIDE WEB ELEMENTS
    ========================================== */

    nav,
    aside,
    header,
    footer{

        display:none !important;

    }

    .print\:hidden{

        display:none !important;

    }

    .print\:block{

        display:block !important;

    }

    h1{

        display:none !important;

    }

    /* ==========================================
       REMOVE DASHBOARD EFFECTS
    ========================================== */

    .shadow,
    .shadow-lg{

        box-shadow:none !important;

    }

    .rounded-lg,
    .rounded-xl,
    .rounded-2xl{

        border-radius:0 !important;

    }

    /* Remove gradient backgrounds for printing */

    [class*="bg-gradient"]{

        background:#ffffff !important;
        color:#000 !important;

    }

    /* ==========================================
       COMPACT SPACING
    ========================================== */

    .mb-8{

        margin-bottom:10px !important;

    }

    .mt-8{

        margin-top:10px !important;

    }

    .p-5{

        padding:8px !important;

    }

    .p-6{

        padding:8px !important;

    }

    .p-8{

        padding:8px !important;

    }

    /* ==========================================
       KPI GRID
    ========================================== */

    .grid{

        gap:6px !important;

    }

    /* ==========================================
       TABLE
    ========================================== */

    table{

        font-size:10px !important;

    }

    th,
    td{

        padding:5px !important;

    }

    thead{

        display:table-header-group;

    }

    tr{

        page-break-inside:avoid;

    }

    /* ==========================================
       AVOID BREAKING SECTIONS
    ========================================== */

    .bg-white,
    .bg-blue-50,
    .bg-yellow-50{

        page-break-inside:avoid;

    }

}

</style>

@endsection