<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Attendance Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        @page{

            size:A4 landscape;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>Carmona Campus</div>

<div>Carmona City, Cavite</div>

</td>

<td width="90"></td>

</tr>

</table>

<hr>

<h2 class="text-center">
    UTILITY & MAINTENANCE STAFF ATTENDANCE REPORT
</h2>

<p class="text-center">
    @if($dateFrom || $dateTo)
        ({{ $dateFrom ?? 'earliest' }} to {{ $dateTo ?? 'latest' }})
    @endif
</p>

<table class="section">

<tr>
<td><strong>Generated Date</strong></td>
<td>{{ now()->format('F d, Y h:i A') }}</td>
<td><strong>Generated By</strong></td>
<td>{{ auth()->user()->fullname ?? auth()->user()->name }}</td>
</tr>

<tr>
<td><strong>Present</strong></td>
<td>{{ $presentCount }}</td>
<td><strong>Late</strong></td>
<td>{{ $lateCount }}</td>
</tr>

<tr>
<td><strong>No Show</strong></td>
<td>{{ $noShowCount }}</td>
<td><strong>Incomplete</strong></td>
<td>{{ $incompleteCount }}</td>
</tr>

<tr>
<td><strong>Total Overtime</strong></td>
<td colspan="3">{{ floor($totalOvertimeMinutes / 60) }}h {{ $totalOvertimeMinutes % 60 }}m</td>
</tr>

</table>

<table class="section">

<thead>

<tr>
<th>Date</th>
<th>Staff</th>
<th>Task</th>
<th>Shift</th>
<th>Time In</th>
<th>Time Out</th>
<th>Status</th>
<th>Overtime</th>
</tr>

</thead>

<tbody>

@forelse($entries as $entry)

@php
    $status = $entry->attendanceStatus();
    $statusInfo = \App\Models\UtilitySchedule::attendanceStatusLabel($status);
@endphp

<tr>
<td>{{ $entry->schedule_date->format('M d, Y') }}</td>
<td>{{ $entry->personnel->fullname ?? '-' }}</td>
<td>{{ $entry->task }}</td>
<td class="text-center">
    @if($entry->shift_start || $entry->shift_end)
        {{ $entry->shift_start ? \Illuminate\Support\Carbon::parse($entry->shift_start)->format('g:i A') : '?' }}
        –
        {{ $entry->shift_end ? \Illuminate\Support\Carbon::parse($entry->shift_end)->format('g:i A') : '?' }}
    @else
        -
    @endif
</td>
<td class="text-center">{{ $entry->time_in?->format('g:i A') ?? '-' }}</td>
<td class="text-center">{{ $entry->time_out?->format('g:i A') ?? '-' }}</td>
<td class="text-center">{{ $statusInfo['label'] }}</td>
<td class="text-center">
    {{ $entry->overtime_minutes > 0 ? $entry->overtime_minutes . ' min' : '-' }}
    @if($entry->overtime_reason)
        <br><em>"{{ $entry->overtime_reason }}"</em>
    @endif
</td>
</tr>

@empty

<tr>
<td colspan="8" class="text-center">No schedule entries match these filters.</td>
</tr>

@endforelse

</tbody>

</table>

</body>

</html>
