<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Utility Schedule
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;
            vertical-align:top;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .entry{

            margin-bottom:4px;

        }

        @page{

            size:A4 landscape;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>Carmona Campus</div>

<div>Carmona City, Cavite</div>

</td>

<td width="90"></td>

</tr>

</table>

<hr>

<h2 class="text-center">
    UTILITY & MAINTENANCE STAFF SCHEDULE
</h2>

<p class="text-center">
    {{ $weekStart->format('F d') }} – {{ $weekEnd->format('F d, Y') }}
</p>

<table class="section">

<tr>
<td><strong>Generated Date</strong></td>
<td>{{ now()->format('F d, Y h:i A') }}</td>
<td><strong>Generated By</strong></td>
<td>{{ auth()->user()->fullname ?? auth()->user()->name }}</td>
</tr>

</table>

<table class="section">

<thead>

<tr>
<th>Staff</th>
@foreach($weekDays as $day)
    <th>{{ $day->format('D, M d') }}</th>
@endforeach
</tr>

</thead>

<tbody>

@forelse($staff as $person)

<tr>
<td><strong>{{ $person->fullname }}</strong><br>{{ $person->positionRecord->position_name ?? '-' }}</td>

@foreach($weekDays as $day)

@php
    $cellKey = $person->id . '_' . $day->format('Y-m-d');
    $cellEntries = $entriesByCell->get($cellKey, collect());
@endphp

<td>
    @forelse($cellEntries as $entry)
        <div class="entry">
            <strong>{{ $entry->task }}</strong><br>
            @if($entry->shift_start || $entry->shift_end)
                {{ $entry->shift_start ? \Illuminate\Support\Carbon::parse($entry->shift_start)->format('g:i A') : '?' }}
                –
                {{ $entry->shift_end ? \Illuminate\Support\Carbon::parse($entry->shift_end)->format('g:i A') : '?' }}<br>
            @endif
            @if($entry->location)
                {{ $entry->location }}
            @endif
        </div>
    @empty
        -
    @endforelse
</td>

@endforeach

</tr>

@empty

<tr>
<td colspan="8" class="text-center">No Utility & Maintenance Staff on record yet.</td>
</tr>

@endforelse

</tbody>

</table>

</body>

</html>
