<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Project Estimate Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .text-right{

            text-align:right;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        @page{

            size:A4 landscape;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>Carmona Campus</div>

<div>Carmona City, Cavite</div>

</td>

<td width="90"></td>

</tr>

</table>

<hr>

<h2 class="text-center">
    PROJECT ESTIMATE REPORT
</h2>

<p class="text-center">
    @if($dateFrom || $dateTo)
        ({{ $dateFrom ?? 'earliest' }} to {{ $dateTo ?? 'latest' }})
    @endif
</p>

<table class="section">

<tr>
<td><strong>Generated Date</strong></td>
<td>{{ now()->format('F d, Y h:i A') }}</td>
<td><strong>Generated By</strong></td>
<td>{{ auth()->user()->fullname ?? auth()->user()->name }}</td>
</tr>

<tr>
<td><strong>Total Estimates</strong></td>
<td>{{ $totalEstimates }}</td>
<td><strong>Total Estimated Value</strong></td>
<td>₱{{ number_format($totalValue, 2) }}</td>
</tr>

<tr>
<td><strong>Materials / Equipment</strong></td>
<td>₱{{ number_format($totalMaterials, 2) }}</td>
<td><strong>Labor</strong></td>
<td>₱{{ number_format($totalLabor, 2) }}</td>
</tr>

</table>

<table class="section">

<thead>
<tr>
    <th>Reference No.</th>
    <th>Project Name</th>
    <th>Location</th>
    <th>Items</th>
    <th>Materials / Equipment</th>
    <th>Labor</th>
    <th>Total</th>
    <th>Prepared By</th>
    <th>Created</th>
</tr>
</thead>

<tbody>

@forelse($estimates as $estimate)

<tr>
<td>{{ $estimate->reference_no }}</td>
<td>{{ $estimate->project_name }}</td>
<td>{{ $estimate->location ?? '-' }}</td>
<td class="text-center">{{ $estimate->items->count() }}</td>
<td class="text-right">{{ number_format($estimate->materialsTotal(), 2) }}</td>
<td class="text-right">{{ number_format($estimate->laborTotal(), 2) }}</td>
<td class="text-right">{{ number_format($estimate->grandTotal(), 2) }}</td>
<td>{{ $estimate->preparer->fullname ?? $estimate->preparer->name }}</td>
<td class="text-center">{{ $estimate->created_at->format('M d, Y') }}</td>
</tr>

@empty

<tr>
<td colspan="9" class="text-center">No project estimates match these filters.</td>
</tr>

@endforelse

</tbody>

</table>

</body>

</html>
