<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Job Request Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        @page{

            size:A4 landscape;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>CvSU Carmona Campus</div>

<div>Carmona, Cavite</div>

<div>(046) 487-6328</div>

<div><a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a></div>

</td>

<td width="90">

<img
src="{{ asset('images/bagong-pilipinas.png') }}"
width="80">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">
    JOB REQUEST REPORT
</h2>

<p class="text-center">
    Completed Job Requests
    @if($dateFrom || $dateTo)
        ({{ $dateFrom ?? 'earliest' }} to {{ $dateTo ?? 'latest' }})
    @endif
    @if($category)
        — {{ $category === 'physical_plant' ? 'Physical Plant & Services' : 'Utility Personnel' }}
    @endif
</p>

<table class="section">

<tr>
<td><strong>Generated Date</strong></td>
<td>{{ now()->format('F d, Y h:i A') }}</td>
<td><strong>Generated By</strong></td>
<td>{{ auth()->user()->fullname ?? auth()->user()->name }}</td>
</tr>

<tr>
<td><strong>Total Completed</strong></td>
<td>{{ $totalCompleted }}</td>
<td><strong>Total Evidence Photos</strong></td>
<td>{{ $totalPhotos }}</td>
</tr>

</table>

<table class="section">

<thead>

<tr>
<th>Reference No.</th>
<th>Requesting Party</th>
<th>Nature of Request</th>
<th>Category</th>
<th>Assigned Personnel</th>
<th>Approved By</th>
<th>Date Completed</th>
<th>Photos</th>
</tr>

</thead>

<tbody>

@forelse($completedJobs as $job)

<tr>
<td>{{ $job->reference_no }}</td>
<td>{{ $job->requesting_party }}</td>
<td>{{ $job->nature_of_request }}</td>
<td class="text-center">{{ $job->categoryLabel() }}</td>
<td>
    @forelse($job->assignedPersonnel as $person)
        {{ $person->fullname }}@if(!$loop->last)<br>@endif
    @empty
        -
    @endforelse
</td>
<td>{{ $job->approver->fullname ?? $job->approver->name ?? '-' }}</td>
<td class="text-center">{{ $job->completed_at?->format('M d, Y') ?? '-' }}</td>
<td class="text-center">{{ $job->photos->count() }}</td>
</tr>

@empty

<tr>
<td colspan="8" class="text-center">No completed job requests match these filters.</td>
</tr>

@endforelse

</tbody>

</table>

</body>

</html>
