<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Utility Leave Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        @page{

            size:A4 landscape;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>CvSU Carmona Campus</div>

<div>Carmona, Cavite</div>

<div>(046) 487-6328</div>

<div><a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a></div>

</td>

<td width="90">

<img
src="{{ asset('images/bagong-pilipinas.png') }}"
width="80">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">
    UTILITY & MAINTENANCE STAFF LEAVE REPORT
</h2>

<p class="text-center">
    @if($dateFrom || $dateTo)
        ({{ $dateFrom ?? 'earliest' }} to {{ $dateTo ?? 'latest' }})
    @endif
</p>

<table class="section">

<tr>
<td><strong>Generated Date</strong></td>
<td>{{ now()->format('F d, Y h:i A') }}</td>
<td><strong>Generated By</strong></td>
<td>{{ auth()->user()->fullname ?? auth()->user()->name }}</td>
</tr>

<tr>
<td><strong>Pending</strong></td>
<td>{{ $pendingCount }}</td>
<td><strong>Approved / Rejected</strong></td>
<td>{{ $approvedCount }} / {{ $rejectedCount }}</td>
</tr>

</table>

<table class="section">

<thead>
<tr>
    <th>Staff</th>
    <th>Type</th>
    <th>Reason</th>
    <th>Date From</th>
    <th>Date To</th>
    <th>Status</th>
    <th>Notes</th>
</tr>
</thead>

<tbody>

@forelse($leaves as $leave)

<tr>
<td>{{ $leave->personnel->fullname ?? 'N/A' }}</td>
<td>{{ $leave->leave_type }}</td>
<td>{{ $leave->reason }}</td>
<td class="text-center">{{ $leave->start_date->format('M d, Y') }}</td>
<td class="text-center">{{ $leave->end_date->format('M d, Y') }}</td>
<td class="text-center">{{ $leave->status }}</td>
<td>{{ $leave->status === 'Rejected' ? ($leave->rejection_reason ?? '-') : '-' }}</td>
</tr>

@empty

<tr>
<td colspan="7" class="text-center">No leave requests match these filters.</td>
</tr>

@endforelse

</tbody>

</table>

</body>

</html>
