<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Purchase Forecast Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>CvSU Carmona Campus</div>

<div>Carmona, Cavite</div>

<div>(046) 487-6328</div>

<div><a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a></div>

</td>

<td width="90">

<img
src="{{ asset('images/bagong-pilipinas.png') }}"
width="80">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

PURCHASE FORECAST REPORT

</h2>

<p class="text-center">

Planning Year {{ $year }}

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

PFR-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

For planning year {{ $year }}, total forecasted procurement spend across all PPMP line items is ₱{{ number_format($annualTotal, 2) }}, distributed across {{ $byDepartment->count() }} department(s) over the four quarters.

</p>

<table>

<tr>

@foreach($quarterTotals as $quarter => $totals)
<th>{{ $quarter }}</th>
@endforeach

<th>Annual Total</th>

</tr>

<tr>

@foreach($quarterTotals as $quarter => $totals)
<td class="text-center">₱{{ number_format($totals['cost'], 2) }}</td>
@endforeach

<td class="text-center">₱{{ number_format($annualTotal, 2) }}</td>

</tr>

</table>

<h3 class="section">

Quarterly Forecast by Department

</h3>

<table>

<thead>

<tr>

<th>Department</th>

<th>Q1</th>

<th>Q2</th>

<th>Q3</th>

<th>Q4</th>

<th>Total</th>

</tr>

</thead>

<tbody>

@forelse($byDepartment as $department => $row)

<tr>

<td>{{ $department }}</td>

<td class="text-center">₱{{ number_format($row['q1'], 2) }}</td>

<td class="text-center">₱{{ number_format($row['q2'], 2) }}</td>

<td class="text-center">₱{{ number_format($row['q3'], 2) }}</td>

<td class="text-center">₱{{ number_format($row['q4'], 2) }}</td>

<td class="text-center">₱{{ number_format($row['total'], 2) }}</td>

</tr>

@empty

<tr>

<td colspan="6" class="text-center">No procurement plan items found for {{ $year }}.</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

Coordinate delivery schedules with suppliers ahead of quarters with the heaviest forecasted spend. Review this forecast against actual budget allocation in the Budget Monitoring report to confirm feasibility.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
