<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Procurement Calendar Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

@php
    $createdCount = $events->where('type', 'created')->count();
    $submittedCount = $events->where('type', 'submitted')->count();
    $approvedCount = $events->where('type', 'approved')->count();
    $rejectedCount = $events->where('type', 'rejected')->count();
@endphp

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>CvSU Carmona Campus</div>

<div>Carmona, Cavite</div>

<div>(046) 487-6328</div>

<div><a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a></div>

</td>

<td width="90">

<img
src="{{ asset('images/bagong-pilipinas.png') }}"
width="80">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

PROCUREMENT CALENDAR REPORT

</h2>

<p class="text-center">

Planning Year {{ $year }}

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

PCR-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

For planning year {{ $year }}, {{ $createdCount }} procurement plan(s) were created, {{ $submittedCount }} submitted for approval, {{ $approvedCount }} approved, and {{ $rejectedCount }} rejected.

</p>

<h3 class="section">

Procurement Plan Timeline

</h3>

<table>

<thead>

<tr>

<th>Date</th>

<th>Event</th>

<th>Plan No.</th>

<th>Department</th>

</tr>

</thead>

<tbody>

@forelse($events as $event)

<tr>

<td>{{ $event['date']?->format('M d, Y h:i A') }}</td>

<td>{{ $event['label'] }}</td>

<td>{{ $event['plan']->plan_number }}</td>

<td>{{ $event['plan']->department->department_name ?? 'Unassigned' }}</td>

</tr>

@empty

<tr>

<td colspan="4" class="text-center">No procurement plan activity found for {{ $year }}.</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

Follow up on plans that have remained in Draft or Submitted status for an extended period. Use this timeline to anticipate upcoming approval workload.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
