<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Department Summary Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>CvSU Carmona Campus</div>

<div>Carmona, Cavite</div>

<div>(046) 487-6328</div>

<div><a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a></div>

</td>

<td width="90">

<img
src="{{ asset('images/bagong-pilipinas.png') }}"
width="80">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

DEPARTMENT SUMMARY REPORT

</h2>

<p class="text-center">

Inventory Distribution by Department

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

DSR-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

This report distributes {{ $totalMaterials }} materials across {{ $totalDepartments }} department(s), totaling {{ number_format($totalQuantity) }} units on hand. {{ $departmentsWithIssues }} department(s) currently have materials at critical, low, or out-of-stock levels.

</p>

<table>

<tr>

<th>Total Departments</th>

<th>Total Materials</th>

<th>Total Quantity</th>

<th>Needing Attention</th>

</tr>

<tr>

<td class="text-center">{{ $totalDepartments }}</td>

<td class="text-center">{{ $totalMaterials }}</td>

<td class="text-center">{{ number_format($totalQuantity) }}</td>

<td class="text-center">{{ $departmentsWithIssues }}</td>

</tr>

</table>

<h3 class="section">

Department Inventory Distribution

</h3>

<table>

<thead>

<tr>

<th>Department</th>

<th>Materials</th>

<th>Total Quantity</th>

<th>Critical</th>

<th>Low Stock</th>

<th>Out of Stock</th>

<th>Status</th>

</tr>

</thead>

<tbody>

@forelse($departmentRows as $row)

@php
    $hasIssues = ($row->critical_count + $row->low_count + $row->out_of_stock_count) > 0;
@endphp

<tr>

<td>{{ $row->department_name }}</td>

<td class="text-center">{{ $row->total_materials }}</td>

<td class="text-center">{{ number_format($row->total_quantity) }}</td>

<td class="text-center">{{ $row->critical_count }}</td>

<td class="text-center">{{ $row->low_count }}</td>

<td class="text-center">{{ $row->out_of_stock_count }}</td>

<td class="text-center">{{ $hasIssues ? 'Needs Attention' : 'Healthy' }}</td>

</tr>

@empty

<tr>

<td colspan="7" class="text-center">No department data available.</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

Departments flagged "Needs Attention" should be prioritized for procurement follow-up. Coordinate with department heads on upcoming material needs to keep stock distribution balanced.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
