@extends('layouts.app')

@section('content')

<div class="bg-white rounded-xl shadow-lg p-6 lg:p-8">

    <!-- Header -->

    <div class="flex justify-between items-start mb-6">

        <div>

            <h2 class="text-3xl lg:text-4xl font-bold text-gray-800 flex items-center gap-3">
                📄 Executive Inventory Summary
            </h2>

            <p class="text-gray-500 text-lg mt-2 max-w-4xl leading-relaxed">
                Inventory Performance and Management Assessment
            </p>

            <div class="mt-6 border border-gray-200 rounded-xl p-5 bg-gray-50">

                <div class="grid grid-cols-2 gap-4 text-base text-gray-700">

                    <div>
                        <span class="font-semibold">Report No.</span>
                        <p class="mt-1">EXE-{{ now()->format('YmdHis') }}</p>
                    </div>

                    <div>
                        <span class="font-semibold">Office</span>
                        <p class="mt-1">General Services Office</p>
                    </div>

                    <div>
                        <span class="font-semibold">Generated Date</span>
                        <p class="mt-1">{{ now()->format('F d, Y h:i A') }}</p>
                    </div>

                    <div>
                        <span class="font-semibold">Generated By</span>
                        <p class="mt-1">{{ auth()->user()->fullname ?? auth()->user()->name }}</p>
                    </div>

                </div>

            </div>

        </div>

        <button
            onclick="window.open('{{ route('inventory.executive.print') }}','_blank')"
            class="bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded">

            🖨 Print Official Report

        </button>

    </div>


    <!-- KPI Cards -->

    @php
        $healthGradients = [
            'green' => 'from-green-600 to-green-700',
            'blue' => 'from-blue-600 to-blue-700',
            'yellow' => 'from-yellow-500 to-yellow-600',
            'red' => 'from-red-600 to-red-700',
        ];
    @endphp

    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mb-8">

        <div class="bg-gradient-to-r {{ $healthGradients[$statusColor] ?? $healthGradients['red'] }} rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-white/80">Inventory Health</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $inventoryHealth }}%</h2>
                    <p class="text-white/80 mt-1">{{ $healthStatus }}</p>
                </div>
                <div class="text-5xl opacity-70">📈</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-blue-600 to-blue-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-blue-100">Available Materials</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $availableMaterials }}</h2>
                </div>
                <div class="text-5xl opacity-70">✅</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-red-600 to-red-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-red-100">Needs Attention</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $criticalStock + $lowStock + $outOfStock }}</h2>
                </div>
                <div class="text-5xl opacity-70">⚠️</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-purple-600 to-purple-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-purple-100">Expiring Soon</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $expiringSoon }}</h2>
                </div>
                <div class="text-5xl opacity-70">⏳</div>
            </div>
        </div>

    </div>


    <!-- Executive Assessment -->

    <div class="bg-blue-50 border border-blue-200 rounded-xl shadow-sm p-6 mb-8">

        <h2 class="text-3xl font-bold text-blue-800 mb-6">

            📊 Executive Assessment

        </h2>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">

            {{-- Inventory Health --}}
            <div>

                <p class="text-gray-500 uppercase text-sm">
                    Inventory Health
                </p>

                <h2 class="text-4xl font-bold mt-2">

                    {{ number_format($inventoryHealth,1) }}%

                </h2>

            </div>

            {{-- Overall Status --}}
            <div>

                <p class="text-gray-500 uppercase text-sm">
                    Overall Status
                </p>

                <h2 class="text-3xl font-bold mt-2
                    @if($statusColor=='green') text-green-600
                    @elseif($statusColor=='blue') text-blue-600
                    @elseif($statusColor=='yellow') text-yellow-500
                    @else text-red-600
                    @endif">

                    {{ strtoupper($healthStatus) }}

                </h2>

            </div>

            {{-- Available Materials --}}
            <div>

                <p class="text-gray-500 uppercase text-sm">
                    Available Materials
                </p>

                <h2 class="text-4xl font-bold mt-2 text-green-600">

                    {{ $availableMaterials }}

                </h2>

            </div>

        </div>

        <hr class="my-6">

        <h3 class="text-xl font-semibold mb-3">

            Management Recommendation

        </h3>

        <p class="text-lg leading-8 text-gray-700">

            {{ $recommendation }}

        </p>

    </div>


    <!-- Top Critical Materials -->

    <div class="border rounded-lg bg-gray-50">

        <div class="border-b p-5">

            <h2 class="text-2xl font-bold">

                Top 10 Critical Materials

            </h2>

        </div>

        <table class="w-full">

            <thead class="bg-gray-100">

                <tr>

                    <th class="p-3 text-left">

                        Material

                    </th>

                    <th class="p-3">

                        Department

                    </th>

                    <th class="p-3">

                        Quantity

                    </th>

                    <th class="p-3">

                        Status

                    </th>

                    <th class="p-3">

                        Priority

                    </th>

                </tr>

            </thead>

        <tbody>

            @forelse($topCritical as $material)

                <tr class="border-t">

                    <td class="p-3">

                        {{ $material->name }}

                    </td>

                    <td class="text-center">

                        {{ $material->department->department_name ?? '-' }}

                    </td>

                    <td class="text-center font-bold">

                        {{ $material->quantity }}

                    </td>

                    <td class="text-center">

                        @php
                            $badges = [
                                'out_of_stock' => ['Out of Stock', 'bg-black'],
                                'critical' => ['Critical', 'bg-red-600'],
                                'low' => ['Low Stock', 'bg-yellow-500'],
                                'available' => ['Available', 'bg-green-600'],
                            ];
                        @endphp

                        <span class="{{ $badges[$material->stock_status][1] }} text-white px-3 py-1 rounded-full text-xs">
                            {{ $badges[$material->stock_status][0] }}
                        </span>

                    </td>

                    <td class="text-center">

                        @php
                            $priorities = [
                                'out_of_stock' => '🔥 Urgent',
                                'critical' => '🔴 High',
                                'low' => '🟡 Medium',
                                'available' => '🟢 Low',
                            ];
                        @endphp

                        {{ $priorities[$material->stock_status] }}

                    </td>

                </tr>

            @empty

                <tr>

                    <td colspan="3" class="text-center p-6">

                        No critical materials.

                    </td>

                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <!-- ==========================================
         Inventory Distribution
    ========================================== -->

<div class="border rounded-lg bg-gray-50 mt-8">

    <div class="border-b p-5">

        <h2 class="text-2xl font-bold">

            📊 Inventory Distribution

        </h2>

    </div>

    <div class="p-6 space-y-6">

        <!-- Available -->

        <div>

            <div class="flex justify-between mb-1">

                <span class="font-semibold">

                    Available Materials

                </span>

                <span>

                    {{ $availableMaterials }}
                    ({{ $availablePercent }}%)

                </span>

            </div>

            <div class="w-full bg-gray-200 rounded-full h-4">

                <div
                    class="bg-green-600 h-4 rounded-full"
                    style="width: {{ $availablePercent }}%;">

                </div>

            </div>

        </div>

        <!-- Critical -->

        <div>

            <div class="flex justify-between mb-1">

                <span class="font-semibold">

                    Critical Stock

                </span>

                <span>

                    {{ $criticalStock }}
                    ({{ $criticalPercent }}%)

                </span>

            </div>

            <div class="w-full bg-gray-200 rounded-full h-4">

                <div
                    class="bg-red-600 h-4 rounded-full"
                    style="width: {{ $criticalPercent }}%;">

                </div>

            </div>

        </div>

        <!-- Low Stock -->

        <div>

            <div class="flex justify-between mb-1">

                <span class="font-semibold">

                    Low Stock

                </span>

                <span>

                    {{ $lowStock }}
                    ({{ $lowPercent }}%)

                </span>

            </div>

            <div class="w-full bg-gray-200 rounded-full h-4">

                <div
                    class="bg-yellow-500 h-4 rounded-full"
                    style="width: {{ $lowPercent }}%;">

                </div>

            </div>

        </div>

        <!-- Out of Stock -->

        <div>

            <div class="flex justify-between mb-1">

                <span class="font-semibold">

                    Out of Stock

                </span>

                <span>

                    {{ $outOfStock }}
                    ({{ $outPercent }}%)

                </span>

            </div>

            <div class="w-full bg-gray-200 rounded-full h-4">

                <div
                    class="bg-gray-700 h-4 rounded-full"
                    style="width: {{ $outPercent }}%;">

                </div>

            </div>

        </div>

        <!-- Expiring Soon -->

        <div>

            <div class="flex justify-between mb-1">

                <span class="font-semibold">

                    Expiring Soon

                </span>

                <span>

                    {{ $expiringSoon }}
                    ({{ $expiringPercent }}%)

                </span>

            </div>

            <div class="w-full bg-gray-200 rounded-full h-4">

                <div
                    class="bg-purple-600 h-4 rounded-full"
                    style="width: {{ $expiringPercent }}%;">

                </div>

            </div>

        </div>

    </div>

</div>

<!-- ==========================================
     Department Impact Analysis
========================================== -->

<div class="border rounded-lg bg-gray-50 mt-8">

    <div class="border-b p-5">

        <h2 class="text-2xl font-bold">

            🏢 Department Impact Analysis

        </h2>

        <p class="text-gray-500 mt-1">

            Departments with inventory materials requiring attention.

        </p>

    </div>

    <div class="overflow-x-auto">

        <table class="w-full">

            <thead class="bg-gray-100">

                <tr>

                    <th class="p-3 text-left">
                        Department
                    </th>

                    <th class="p-3 text-center">
                        Total Materials
                    </th>

                    <th class="p-3 text-center">
                        Affected Materials
                    </th>

                    <th class="p-3 text-center">
                        Impact Level
                    </th>

                </tr>

            </thead>

            <tbody>

            @forelse($departmentImpact as $department)

                @php
                    $impactPercent = $department->total_materials > 0
                        ? round(($department->affected_materials / $department->total_materials) * 100)
                        : 0;
                @endphp

                <tr class="border-t hover:bg-gray-50">

                    <td class="p-3 font-semibold">

                        {{ $department->department->department_name ?? 'Unknown Department' }}

                    </td>

                    <td class="text-center">

                        {{ $department->total_materials }}

                    </td>

                    <td class="text-center font-bold">

                        {{ $department->affected_materials }}

                    </td>

                    <td class="text-center">

                        @if($impactPercent >= 75)

                            <span class="bg-red-600 text-white px-3 py-1 rounded-full text-xs">

                                High Impact

                            </span>

                        @elseif($impactPercent >= 40)

                            <span class="bg-yellow-500 text-white px-3 py-1 rounded-full text-xs">

                                Medium Impact

                            </span>

                        @else

                            <span class="bg-green-600 text-white px-3 py-1 rounded-full text-xs">

                                Low Impact

                            </span>

                        @endif

                    </td>

                </tr>

            @empty

                <tr>

                    <td colspan="4" class="text-center py-6 text-gray-500">

                        No department data available.

                    </td>

                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

</div>

</div>

@endsection