<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Executive Inventory Summary
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{
            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        th,
        td{
            border:1px solid #000;
            padding:6px;
        }

        th{
            background:#e5e7eb;
        }

        .text-center{
            text-align:center;
        }

        .header-table td{
            border:none;
        }

        .signature td{
            border:none;
            padding-top:60px;
        }

        .section{
            margin-top:25px;
        }

        h1,h2,h3,h4{
            margin:3px;
        }

        @page{
            size:A4 portrait;
            margin:12mm;
        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>CvSU Carmona Campus</div>

<div>Carmona, Cavite</div>

<div>(046) 487-6328</div>

<div><a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a></div>

</td>

<td width="90">

<img
src="{{ asset('images/bagong-pilipinas.png') }}"
width="80">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

EXECUTIVE INVENTORY SUMMARY

</h2>

<p class="text-center">

Inventory Performance and Management Assessment

</p>

<table class="section">

<tr>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

</tr>

</table>

<h3 class="section">

Executive Assessment

</h3>

<p>

This report provides an executive overview of the current
inventory condition of the General Services Office.

It summarizes inventory health, available materials,
critical inventory, procurement priorities and operational
recommendations to support management decision making.

</p>

<h3 class="section">

Inventory Statistics

</h3>

<table>

<tr>

<th>Total Materials</th>

<th>Inventory Health</th>

<th>Available</th>

<th>Critical</th>

<th>Low Stock</th>

<th>Out of Stock</th>

</tr>

<tr>

<td class="text-center">

{{ $totalMaterials }}

</td>

<td class="text-center">

{{ $inventoryHealth }}%

</td>

<td class="text-center">

{{ $availableMaterials }}

</td>

<td class="text-center">

{{ $criticalStock }}

</td>

<td class="text-center">

{{ $lowStock }}

</td>

<td class="text-center">

{{ $outOfStock }}

</td>

</tr>

</table>

<h3 class="section">

Top 10 Critical Materials

</h3>

<table>

<thead>

<tr>

<th>#</th>

<th>Material</th>

<th>Department</th>

<th>Quantity</th>

</tr>

</thead>

<tbody>

@forelse($topCritical as $material)

<tr>

<td class="text-center">

{{ $loop->iteration }}

</td>

<td>

{{ $material->name }}

</td>

<td>

{{ $material->department->department_name ?? '-' }}

</td>

<td class="text-center">

{{ $material->quantity }}

</td>

</tr>

@empty

<tr>

<td colspan="4" class="text-center">

No critical materials found.

</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Management Recommendation

</h3>

<ul>

<li>Continue monitoring inventory health regularly.</li>

<li>Prioritize procurement of critical materials.</li>

<li>Review reorder thresholds monthly.</li>

<li>Conduct periodic inventory validation.</li>

<li>Maintain inventory health above 90%.</li>

</ul>

<table class="signature">

<tr>

<td class="text-center">

_________________________<br>
Prepared By

</td>

<td class="text-center">

_________________________<br>
Reviewed By

</td>

<td class="text-center">

_________________________<br>
Approved By

</td>

</tr>

</table>

</body>

</html>