<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Expiration Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>

Republic of the Philippines

</div>

<h2>

CAVITE STATE UNIVERSITY

</h2>

<div>

Carmona Campus

</div>

<h4>

GENERAL SERVICES OFFICE

</h4>

</td>

<td width="90">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

EXPIRATION REPORT

</h2>

<p class="text-center">

Expiring and Expired Inventory Batches

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

EXP-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

This report identifies inventory batches expiring within 30 days
and batches that have already expired, so departments can
prioritize consumption and disposal accordingly.

</p>

<table>

<tr>

<th>Expiring Within 30 Days</th>

<th>Expired Batches</th>

<th>Departments Affected</th>

</tr>

<tr>

<td class="text-center">

{{ $expiringCount }}

</td>

<td class="text-center">

{{ $expiredCount }}

</td>

<td class="text-center">

{{ $departmentsAffected }}

</td>

</tr>

</table>

<h3 class="section">

Expiring Within 30 Days

</h3>

<table>

<thead>

<tr>

<th width="40">#</th>

<th>Material</th>

<th>Department</th>

<th>Batch No.</th>

<th>Remaining</th>

<th>Expiration Date</th>

<th>Days Left</th>

</tr>

</thead>

<tbody>

@forelse($expiringMaterials as $batch)

<tr>

<td class="text-center">{{ $loop->iteration }}</td>

<td>{{ $batch->material->name }}</td>

<td>{{ $batch->material->department->department_name ?? '-' }}</td>

<td class="text-center">{{ $batch->batch_no }}</td>

<td class="text-center">{{ $batch->quantity_remaining }}</td>

<td class="text-center">{{ \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') }}</td>

<td class="text-center">{{ now()->diffInDays($batch->expiration_date) }} days</td>

</tr>

@empty

<tr>

<td colspan="7" class="text-center">No materials expiring within 30 days.</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Already Expired

</h3>

<table>

<thead>

<tr>

<th width="40">#</th>

<th>Material</th>

<th>Department</th>

<th>Batch No.</th>

<th>Remaining</th>

<th>Expiration Date</th>

<th>Days Expired</th>

</tr>

</thead>

<tbody>

@forelse($expiredMaterials as $batch)

<tr>

<td class="text-center">{{ $loop->iteration }}</td>

<td>{{ $batch->material->name }}</td>

<td>{{ $batch->material->department->department_name ?? '-' }}</td>

<td class="text-center">{{ $batch->batch_no }}</td>

<td class="text-center">{{ $batch->quantity_remaining }}</td>

<td class="text-center">{{ \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') }}</td>

<td class="text-center">{{ \Carbon\Carbon::parse($batch->expiration_date)->diffInDays(now()) }} days</td>

</tr>

@empty

<tr>

<td colspan="7" class="text-center">No expired inventory batches.</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

Expired batches should be removed from usable stock immediately and logged for disposal. Batches expiring within 30 days should be prioritized for consumption ahead of longer-dated stock.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
