<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Frequently Requested Items Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>Republic of the Philippines</div>

<h2>CAVITE STATE UNIVERSITY</h2>

<div>CvSU Carmona Campus</div>

<div>Carmona, Cavite</div>

<div>(046) 487-6328</div>

<div><a href="https://www.cvsu.edu.ph" style="color:#000;text-decoration:none;">www.cvsu.edu.ph</a></div>

</td>

<td width="90">

<img
src="{{ asset('images/bagong-pilipinas.png') }}"
width="80">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

FREQUENTLY REQUESTED ITEMS REPORT

</h2>

<p class="text-center">

Materials With the Highest Combined Request Demand

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

FRQ-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

This report tracks {{ $frequentlyRequestedCount }} materials out of
{{ $totalMaterials }} in the catalog that have been requested at least
once, ranked by how often they've been requested across Material
Requests and Walk-In Issuances combined.

</p>

<table>

<tr>

<th>Items Tracked</th>

<th>Total Transactions</th>

<th>Total Qty Requested</th>

</tr>

<tr>

<td class="text-center">

{{ $frequentlyRequestedCount }}

</td>

<td class="text-center">

{{ $totalTransactions }}

</td>

<td class="text-center">

{{ $totalQtyRequested }}

</td>

</tr>

</table>

<h3 class="section">

Top {{ $frequentlyRequestedCount }} Requested Materials

</h3>

<table>

<thead>

<tr>

<th width="40">

#

</th>

<th>

Material

</th>

<th>

Department

</th>

<th>

Category

</th>

<th>

Total Transactions

</th>

<th>

Total Qty Requested

</th>

</tr>

</thead>

<tbody>

@forelse($frequentlyRequested as $material)

<tr>

<td class="text-center">

{{ $loop->iteration }}

</td>

<td>

{{ $material->name }}

</td>

<td>

{{ $material->department->department_name ?? '-' }}

</td>

<td>

{{ $material->category->name ?? '-' }}

</td>

<td class="text-center">

{{ $material->total_transactions }}

</td>

<td class="text-center">

{{ $material->total_requested_qty }}

</td>

</tr>

@empty

<tr>

<td colspan="6" class="text-center">

No request activity on record yet.

</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

Prioritize these materials when planning procurement — they see the
most actual use. Consider raising the reorder threshold for the top
items so they don't run out between restocks.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
