<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        INVENTORY SUMMARY REPORT
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .text-right{

            text-align:right;

        }

        .header-table td{

            border:none;

        }

        .no-border{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>

Republic of the Philippines

</div>

<h2>

CAVITE STATE UNIVERSITY

</h2>

<div>

Carmona Campus

</div>

<h4>

GENERAL SERVICES OFFICE

</h4>

</td>

<td width="90">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

INVENTORY SUMMARY STATUS REPORT

</h2>

<p class="text-center">

Materials Currently at Critical Inventory Level

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

CSR-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

This report presents the current inventory status of the
General Services Office. It summarizes the total available
materials, inventory health, low stock items, critical stock,
and out-of-stock materials to assist management in planning,
procurement, and decision-making.

</p>

<table>

    <tr>

        <th>Total Materials</th>

        <th>Available</th>

        <th>Low Stock</th>

        <th>Critical Stock</th>

        <th>Out of Stock</th>

        <th>Inventory Health</th>

    </tr>

    <tr>

        <td class="text-center">

            {{ $totalMaterials }}

        </td>

        <td class="text-center">

            {{ $availableMaterials }}

        </td>

        <td class="text-center">

            {{ $lowStock }}

        </td>

        <td class="text-center">

            {{ $criticalCount }}

        </td>

        <td class="text-center">

            {{ $outOfStock }}

        </td>

        <td class="text-center">

            {{ $health }}%

        </td>

    </tr>

</table>

<h3 class="section">

Critical Inventory Overview

</h3>

<table>

<thead>

    <tr>

        <th>#</th>

        <th>Material</th>

        <th>Department</th>

        <th>Current Quantity</th>

        <th>Status</th>

    </tr>

</thead>

<tbody>

@forelse($criticalMaterials as $material)

<tr>

<td class="text-center">

{{ $loop->iteration }}

</td>

<td>

{{ $material->name }}

</td>

<td>

{{ $material->department->department_name ?? '-' }}

</td>

<td>

{{ $material->category->category_name ?? '-' }}

</td>

<td class="text-center">

{{ $material->quantity }}

</td>

<td class="text-center">

{{ $material->threshold }}

</td>

<td class="text-center">

    @if($material->quantity <= 0)

    Out of Stock

    @elseif($material->quantity <= 5)

    Critical

    @elseif($material->quantity <= $material->threshold)

    Low Stock

    @else

    Available

    @endif

</td>

</tr>

@empty

<tr>

<td colspan="7" class="text-center">

No critical materials found.

</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

    Based on the current inventory assessment, management is advised
    to prioritize procurement of critical and low-stock materials,
    monitor inventory trends regularly, and review reorder thresholds
    to maintain uninterrupted operations and efficient resource
    utilization.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>