@extends('layouts.app')

<style>

@page {

    size: A4 portrait;

    margin: 15mm;

}

.print-summary{
    display:none;
}

.screen-summary{
    display:block;
}



@media print {

   .print-summary{
    display:block !important;
    }

    .screen-summary{
        display:none !important;
    }

    /* Hide website interface */

    aside,
    nav,
    header,
    .sidebar,
    .topbar,
    button,
    .no-print {

        display: none !important;

    }

    body {

        background: white !important;

        margin: 0;

        padding: 0;

    }

    .max-w-6xl {

        max-width: 100% !important;

        width: 100% !important;

        margin: 0 !important;

        padding: 15px !important;

        box-shadow: none !important;

    }

    table {

        width: 100%;

        border-collapse: collapse;

        page-break-inside: auto;

    }

    thead {

        display: table-header-group;

    }

    tr {

        page-break-inside: avoid;

        page-break-after: auto;

    }

    td,
    th {

        border: 1px solid #000 !important;

        padding: 6px;

        color: black !important;

    }

    h1,
    h2,
    h3,
    h4 {

        color: black !important;

    }

}

</style>

@section('content')

<div class="max-w-6xl mx-auto bg-white shadow rounded-lg p-6">

    <!-- ===============================
    OFFICIAL REPORT HEADER
    =============================== -->

    <div class="text-center border-b-2 border-gray-400 pb-5 mb-6">

        <h4 class="text-sm uppercase">
            Republic of the Philippines
        </h4>

        <h2 class="text-2xl font-bold uppercase">
            Cavite State University
        </h2>

        <p class="text-sm">
            Carmona Campus
        </p>

        <h3 class="text-lg font-semibold mt-3 uppercase">
            General Services Office
        </h3>

        <h1 class="text-3xl font-bold mt-3 uppercase tracking-wide">
            Inventory Summary Report
        </h1>

        <p class="text-sm mt-2">
            Report No.:
            INV-{{ now()->format('Ymd-His') }}
        </p>

    </div>

    <div class="flex justify-between items-center mb-6">
        <div>
            <table class="text-sm">
                <tr>
                    <td class="font-semibold pr-3">
                        Report Generated:
                    </td>
                    <td>
                        {{ now()->format('F d, Y h:i A') }}
                    </td>
                </tr>

                <tr>
                    <td class="font-semibold">
                        Generated By:
                    </td>
                    <td>
                        {{ auth()->user()->username }}
                    </td>
                </tr>

                <tr>
                    <td class="font-semibold">
                        Office:
                    </td>
                    <td>
                        General Services Office
                    </td>
                </tr>
            </table>
        </div>

        <button
            onclick="window.print()"
            class="no-print bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded">

            🖨 Print Report

        </button>

    </div>

    <!-- ===============================
    EXECUTIVE DASHBOARD
    =============================== -->

    <div class="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8">

        <h2 class="text-2xl font-bold text-blue-800 mb-4">
            Executive Dashboard
        </h2>

        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">

            <div class="bg-white rounded shadow p-4">
                <h4 class="text-gray-500 text-sm">
                    Inventory Health
                </h4>

                <p class="text-3xl font-bold text-green-700">
                    {{ $inventoryHealth }}%
                </p>

                <p class="text-sm text-gray-600">
                    {{ $healthStatus }}
                </p>
            </div>

            <div class="bg-white rounded shadow p-4">
                <h4 class="text-gray-500 text-sm">
                    Available Materials
                </h4>

                <p class="text-3xl font-bold text-blue-700">
                    {{ $availableMaterials }}
                </p>
            </div>

            <div class="bg-white rounded shadow p-4">
                <h4 class="text-gray-500 text-sm">
                    Needs Attention
                </h4>

                <p class="text-3xl font-bold text-red-700">
                    {{ $criticalStock + $lowStock + $outOfStock }}
                </p>
            </div>

            <div class="bg-white rounded shadow p-4">
                <h4 class="text-gray-500 text-sm">
                    Expiring Soon
                </h4>

                <p class="text-3xl font-bold text-purple-700">
                    {{ $expiringSoon }}
                </p>
            </div>

        </div>

    </div>

        <div class="border rounded-lg p-6 mb-8">

        <h2 class="text-xl font-bold mb-3">
            Executive Assessment
        </h2>

        <ul class="list-disc ml-6 space-y-2">

            <li>Total Inventory Materials:
                <strong>{{ $totalMaterials }}</strong>
            </li>

            <li>Healthy Inventory:
                <strong>{{ $availableMaterials }}</strong>
            </li>

            <li>Critical Stock:
                <strong>{{ $criticalStock }}</strong>
            </li>

            <li>Low Stock:
                <strong>{{ $lowStock }}</strong>
            </li>

            <li>Out of Stock:
                <strong>{{ $outOfStock }}</strong>
            </li>

            <li>Expiring Soon:
                <strong>{{ $expiringSoon }}</strong>
            </li>

        </ul>

    </div>

        <div class="print-summary mt-5">
            <h3 class="text-lg font-bold mb-3">
                Inventory Summary
            </h3>
            <table class="w-full border text-xs">
                <tbody>
                    <tr>
                        <td><strong>Total Materials</strong></td>
                        <td class="text-center">{{ $totalMaterials }}</td>
                    </tr>
                    <tr>
                        <td><strong>Critical Stock</strong></td>
                        <td class="text-center">{{ $criticalStock }}</td>
                    </tr>
                    <tr>
                        <td><strong>Low Stock</strong></td>
                        <td class="text-center">{{ $lowStock }}</td>
                    </tr>
                    <tr>
                        <td><strong>Out of Stock</strong></td>
                        <td class="text-center">{{ $outOfStock }}</td>
                    </tr>
                    <tr>
                        <td><strong>Expiring Soon</strong></td>
                        <td class="text-center">{{ $expiringSoon }}</td>
                    </tr>
                    <tr>
                        <td><strong>Expired Batches</strong></td>
                        <td class="text-center">{{ $expiredItems }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

    <div class="screen-summary grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">

        <div class="border p-5 rounded">
            <h3 class="font-bold text-blue-700">
                Total Materials
            </h3>

            <p class="text-3xl font-bold">
                {{ $totalMaterials }}
            </p>
        </div>

        <div class="border p-5 rounded">
            <h3 class="font-bold text-yellow-700">
                Low Stock
            </h3>

            <p class="text-3xl font-bold">
                {{ $lowStock }}
            </p>
        </div>

        <div class="border p-5 rounded">
            <h3 class="font-bold text-orange-700">
                Critical Stock
            </h3>

            <p class="text-3xl font-bold">
                {{ $criticalStock }}
            </p>
        </div>

        <div class="border p-5 rounded">

            <h3 class="font-bold text-red-700">
                Out of Stock
            </h3>

            <p class="text-3xl font-bold">
                {{ $outOfStock }}
            </p>
        </div>

        <div class="border p-5 rounded">
            <h3 class="font-bold text-purple-700">
                Expiring Soon
            </h3>

            <p class="text-3xl font-bold">
                {{ $expiringSoon }}
            </p>
        </div>

        <div class="border p-5 rounded">
            <h3 class="font-bold text-gray-700">
                Expired Batches
            </h3>

            <p class="text-3xl font-bold">
                {{ $expiredItems }}
            </p>
        </div>

    </div>

    <div class="screen-summary border rounded p-5">

        <h3 class="font-bold text-lg mb-3">
            Report Summary
        </h3>

        <ul class="list-disc pl-6 space-y-2">

            <li>
                Total Inventory Materials:
                <strong>{{ $totalMaterials }}</strong>
            </li>

            <li>
                Low Stock Materials:
                <strong>{{ $lowStock }}</strong>
            </li>

            <li>
                Critical Stock Materials:
                <strong>{{ $criticalStock }}</strong>
            </li>

            <li>
                Out of Stock Materials:
                <strong>{{ $outOfStock }}</strong>
            </li>

            <li>
                Materials Expiring Within 30 Days:
                <strong>{{ $expiringSoon }}</strong>
            </li>

            <li>
                Expired Inventory Batches:
                <strong>{{ $expiredItems }}</strong>
            </li>

        </ul>

    </div>

        <div class="mt-8 border-b pb-2">

            <h2 class="text-lg font-bold uppercase">
                SECTION I. INVENTORY STATUS
            </h2>

            <p class="text-sm text-gray-600">
                Table 1. Critical Stock Materials
            </p>

        </div>

        <table class="w-full border text-xs">

            <thead class="bg-gray-200">

                <tr>

                    <th class="p-2">Material</th>
                    <th class="p-2">Department</th>
                    <th class="p-2">Quantity</th>
                    <th class="p-2">Threshold</th>

                </tr>

            </thead>

            <tbody>

            @forelse($criticalMaterials as $material)

                <tr class="border-t">

                    <td class="p-2 text-center">
                        {{ $material->name }}
                    </td>

                    <td class="p-2 text-center">
                        {{ $material->department->department_name ?? '-' }}
                    </td>

                    <td class="text-center">
                        {{ $material->quantity }}
                    </td>

                    <td class="text-center">
                        {{ $material->threshold }}
                    </td>

                </tr>

            @empty

                <tr>

                    <td colspan="4" class="text-center p-4">
                        No critical materials.
                    </td>

                </tr>

            @endforelse

            </tbody>

        </table>


    <div class="mt-8">

        <div class="mt-10 pt-4 border-t-2 border-gray-500">

            <p class="text-sm font-semibold">
                Table 2. Low Stock Materials
            </p>

        </div>

        <table class="w-full border text-xs">

            <thead class="bg-gray-200">
                <tr>
                    <th class="p-2">Material</th>
                    <th class="p-2">Department</th>
                    <th class="p-2">Quantity</th>
                    <th class="p-2">Threshold</th>
                </tr>
            </thead>

            <tbody>

            @forelse($lowStockMaterials as $material)

                <tr class="border-t">

                    <td class="p-2 text-center">
                        {{ $material->name }}
                    </td>

                    <td class="p-2 text-center">
                        {{ $material->department->department_name ?? '-' }}
                    </td>

                    <td class="text-center">
                        {{ $material->quantity }}
                    </td>

                    <td class="text-center">
                        {{ $material->threshold }}
                    </td>

                </tr>

            @empty

                <tr>
                    <td colspan="4" class="text-center p-4">
                        No low stock materials.
                    </td>
                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="mt-8">

        <div class="mt-10 border-b pb-2">

            <p class="text-sm font-semibold">
                Table 3. Out of Stock Materials
            </p>

        </div>

        <table class="w-full border text-xs">

            <thead class="bg-gray-200">

                <tr>

                    <th class="p-2">Material</th>
                    <th class="p-2">Department</th>
                    <th class="p-2">Category</th>
                    <th class="p-2">Quantity</th>

                </tr>

            </thead>

            <tbody>

            @forelse($outOfStockMaterials as $material)

                <tr class="border-t">

                    <td class="p-2">
                        {{ $material->name }}
                    </td>

                    <td class="p-2">
                        {{ $material->department->department_name ?? '-' }}
                    </td>

                    <td class="p-2">
                        {{ $material->category->name ?? '-' }}
                    </td>

                    <td class="p-2 text-center text-red-600 font-bold">
                        {{ $material->quantity }}
                    </td>

                </tr>

            @empty

                <tr>

                    <td colspan="4" class="text-center p-4">
                        No out of stock materials.
                    </td>

                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="mt-8">

        <div class="mt-10 pt-4 border-t-2 border-gray-500">

            <h2 class="text-lg font-bold uppercase">
                SECTION II. MATERIAL EXPIRATION
            </h2>

            <p class="text-sm text-gray-600">
                Table 4. Materials Expiring Within 30 Days
            </p>

        </div>

        <table class="w-full border text-xs">

            <thead class="bg-gray-200">

                <tr>

                    <th class="p-2">Material</th>
                    <th class="p-2">Department</th>
                    <th class="p-2">Batch No.</th>
                    <th class="p-2">Remaining</th>
                    <th class="p-2">Expiration Date</th>
                    <th class="p-2">Days Left</th>

                </tr>

            </thead>

            <tbody>

            @forelse($expiringMaterials as $batch)

                <tr class="border-t">

                    <td class="p-2">
                        {{ $batch->material->name }}
                    </td>

                    <td class="p-2">
                        {{ $batch->material->department->department_name ?? '-' }}
                    </td>

                    <td class="text-center">
                        {{ $batch->batch_no }}
                    </td>

                    <td class="text-center">
                        {{ $batch->quantity_remaining }}
                    </td>

                    <td class="text-center">
                        {{ \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') }}
                    </td>

                    <td class="text-center text-purple-700 font-bold">
                        {{ now()->diffInDays($batch->expiration_date) }} days
                    </td>

                </tr>

            @empty

                <tr>

                    <td colspan="6" class="text-center p-4">
                        No materials expiring within 30 days.
                    </td>

                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="mt-8">

        <div class="mt-10 border-b pb-2">

            <p class="text-sm font-semibold">
                Table 5. Expired Inventory Batches
            </p>

        </div>

        <table class="w-full border text-xs">

            <thead class="bg-gray-300">

                <tr>

                    <th class="p-2">Material</th>
                    <th class="p-2">Department</th>
                    <th class="p-2">Batch No.</th>
                    <th class="p-2">Remaining</th>
                    <th class="p-2">Expiration Date</th>
                    <th class="p-2">Days Expired</th>

                </tr>

            </thead>

            <tbody>

            @forelse($expiredMaterials as $batch)

                <tr class="border-t">

                    <td class="p-2">
                        {{ $batch->material->name }}
                    </td>

                    <td class="p-2">
                        {{ $batch->material->department->department_name ?? '-' }}
                    </td>

                    <td class="text-center">
                        {{ $batch->batch_no }}
                    </td>

                    <td class="text-center">
                        {{ $batch->quantity_remaining }}
                    </td>

                    <td class="text-center">
                        {{ \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') }}
                    </td>

                    <td class="text-center text-red-600 font-bold">
                        {{ \Carbon\Carbon::parse($batch->expiration_date)->diffInDays(now()) }} days
                    </td>

                </tr>

            @empty

                <tr>

                    <td colspan="6" class="text-center p-4">
                        No expired inventory batches.
                    </td>

                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="mt-8">

        <div class="mt-10 border-b pb-2">

            <h2 class="text-lg font-bold uppercase">
                SECTION III. DEPARTMENT INVENTORY
            </h2>

            <p class="text-sm text-gray-600">
                Table 6. Department Inventory Summary
            </p>

        </div>

        <table class="w-full border text-xs">

            <thead class="bg-gray-200">

                <tr>

                    <th class="p-2">Department</th>
                    <th class="p-2">Materials</th>
                    <th class="p-2">Total Quantity</th>
                    <th class="p-2">Last Release</th>

                </tr>

            </thead>

            <tbody>

            @foreach($departmentSummary as $department)

                <tr class="border-t">

                    <td class="p-2">
                        {{ $department->department_name }}
                    </td>

                    <td class="text-center">
                        {{ $department->total_materials }}
                    </td>

                    <td class="text-center">
                        {{ number_format($department->total_quantity) }}
                    </td>

                    <td class="text-center">
                        {{ $department->last_release
                            ? \Carbon\Carbon::parse($department->last_release)->format('M d, Y')
                            : '-' }}
                    </td>

                </tr>

            @endforeach

            </tbody>

        </table>

    </div>

    <!-- ===============================
    REPORT SIGNATURES
    =============================== -->

    <div class="mt-16">

        <div class="grid grid-cols-3 gap-12 text-center">

            <div>

                <p class="mb-12 font-semibold">
                    Prepared By:
                </p>

                <div class="border-t border-black pt-2">

                    <strong>{{ auth()->user()->username }}</strong><br>

                    <span class="text-sm">
                        Inventory Supervisor
                    </span>

                </div>

            </div>

            <div>

                <p class="mb-12 font-semibold">
                    Checked By:
                </p>

                <div class="border-t border-black pt-2">

                    <strong>____________________</strong><br>

                    <span class="text-sm">
                        General Services Head
                    </span>

                </div>

            </div>

            <div>

                <p class="mb-12 font-semibold">
                    Approved By:
                </p>

                <div class="border-t border-black pt-2">

                    <strong>____________________</strong><br>

                    <span class="text-sm">
                        Campus Administrator
                    </span>

                </div>

            </div>

        </div>

    </div>

</div>

@endsection