@extends('layouts.app')

@section('content')

<div class="max-w-7xl mx-auto">

    <!-- Header -->

    <div class="flex justify-between items-center mb-8">

        <div>

            <h1 class="text-4xl font-bold text-white mt-4">
                Inventory Summary Report
            </h1>

            <p class="text-blue-100 text-lg mt-3 max-w-4xl leading-relaxed">
                Full Inventory Status and Stock Level Overview
            </p>

            <div class="mt-6 bg-white/10 backdrop-blur-sm rounded-xl p-5 border border-white/20">

                <div class="grid grid-cols-2 gap-4 text-sm text-white">

                    <div>
                        <span class="font-semibold">Report No.</span>
                        <p class="mt-1">INV-{{ now()->format('YmdHis') }}</p>
                    </div>

                    <div>
                        <span class="font-semibold">Office</span>
                        <p class="mt-1">General Services Office</p>
                    </div>

                    <div>
                        <span class="font-semibold">Generated Date</span>
                        <p class="mt-1">{{ now()->format('F d, Y h:i A') }}</p>
                    </div>

                    <div>
                        <span class="font-semibold">Generated By</span>
                        <p class="mt-1">{{ auth()->user()->fullname ?? auth()->user()->name }}</p>
                    </div>

                </div>

            </div>

        </div>

        <a
            href="{{ route('inventory.summary.print') }}"
            target="_blank"
            class="bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded">

            🖨 Print Official Report

        </a>

    </div>

    <!-- KPI Cards -->

    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 mb-8">

        <div class="bg-gradient-to-r from-blue-600 to-blue-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-blue-100">Total Materials</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $totalMaterials }}</h2>
                </div>
                <div class="text-5xl opacity-70">📦</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-red-600 to-red-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-red-100">Critical Stock</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $criticalStock }}</h2>
                </div>
                <div class="text-5xl opacity-70">🚨</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-yellow-500 to-yellow-600 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-yellow-100">Low Stock</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $lowStock }}</h2>
                </div>
                <div class="text-5xl opacity-70">⚠️</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-gray-700 to-gray-900 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-gray-300">Out of Stock</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $outOfStock }}</h2>
                </div>
                <div class="text-5xl opacity-70">❌</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-purple-600 to-purple-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-purple-100">Expiring Soon</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $expiringSoon }}</h2>
                </div>
                <div class="text-5xl opacity-70">⏳</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-slate-600 to-slate-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-slate-200">Expired Batches</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $expiredItems }}</h2>
                </div>
                <div class="text-5xl opacity-70">🗑️</div>
            </div>
        </div>

    </div>

    <!-- Executive Assessment -->

    <div class="bg-blue-50 border border-blue-200 rounded-xl shadow-sm p-6 mb-8">

        <h2 class="text-3xl font-bold text-blue-800 mb-6">
            📊 Executive Assessment
        </h2>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">

            <div>
                <p class="text-gray-500 uppercase text-sm">Inventory Health</p>
                <h2 class="text-4xl font-bold mt-2">{{ number_format($inventoryHealth, 1) }}%</h2>
            </div>

            <div>
                <p class="text-gray-500 uppercase text-sm">Overall Status</p>
                <h2 class="text-3xl font-bold mt-2
                    @if($statusColor=='green') text-green-600
                    @elseif($statusColor=='blue') text-blue-600
                    @elseif($statusColor=='yellow') text-yellow-500
                    @else text-red-600
                    @endif">
                    {{ strtoupper($healthStatus) }}
                </h2>
            </div>

            <div>
                <p class="text-gray-500 uppercase text-sm">Available Materials</p>
                <h2 class="text-4xl font-bold mt-2 text-green-600">{{ $availableMaterials }}</h2>
            </div>

        </div>

        <hr class="my-6">

        <h3 class="text-xl font-semibold mb-3">Management Recommendation</h3>

        <p class="text-lg leading-8 text-gray-700">{{ $recommendation }}</p>

    </div>

    <div class="bg-white rounded-lg shadow mt-8">

        <div class="border-b p-5">
            <h2 class="text-2xl font-bold">SECTION I. Critical Stock Materials</h2>
            <p class="text-gray-500 mt-1">Materials at or below 30% of their reorder threshold.</p>
        </div>

        <table class="w-full">

            <thead class="bg-gray-100">
                <tr>
                    <th class="p-3 text-left">Material</th>
                    <th class="p-3">Department</th>
                    <th class="p-3">Quantity</th>
                    <th class="p-3">Threshold</th>
                </tr>
            </thead>

            <tbody>

            @forelse($criticalMaterials as $material)

                <tr class="border-t">
                    <td class="p-3">{{ $material->name }}</td>
                    <td class="text-center">{{ $material->department->department_name ?? '-' }}</td>
                    <td class="text-center font-bold">{{ $material->quantity }}</td>
                    <td class="text-center">{{ $material->threshold }}</td>
                </tr>

            @empty

                <tr>
                    <td colspan="4" class="text-center p-6">No critical materials.</td>
                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="bg-white rounded-lg shadow mt-8">

        <div class="border-b p-5">
            <h2 class="text-2xl font-bold">SECTION II. Low Stock Materials</h2>
            <p class="text-gray-500 mt-1">Below their reorder threshold, but not yet critical.</p>
        </div>

        <table class="w-full">

            <thead class="bg-gray-100">
                <tr>
                    <th class="p-3 text-left">Material</th>
                    <th class="p-3">Department</th>
                    <th class="p-3">Quantity</th>
                    <th class="p-3">Threshold</th>
                </tr>
            </thead>

            <tbody>

            @forelse($lowStockMaterials as $material)

                <tr class="border-t">
                    <td class="p-3">{{ $material->name }}</td>
                    <td class="text-center">{{ $material->department->department_name ?? '-' }}</td>
                    <td class="text-center font-bold">{{ $material->quantity }}</td>
                    <td class="text-center">{{ $material->threshold }}</td>
                </tr>

            @empty

                <tr>
                    <td colspan="4" class="text-center p-6">No low stock materials.</td>
                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="bg-white rounded-lg shadow mt-8">

        <div class="border-b p-5">
            <h2 class="text-2xl font-bold">SECTION III. Out of Stock Materials</h2>
            <p class="text-gray-500 mt-1">Zero quantity on hand — needs immediate procurement.</p>
        </div>

        <table class="w-full">

            <thead class="bg-gray-100">
                <tr>
                    <th class="p-3 text-left">Material</th>
                    <th class="p-3">Department</th>
                    <th class="p-3">Category</th>
                    <th class="p-3">Quantity</th>
                </tr>
            </thead>

            <tbody>

            @forelse($outOfStockMaterials as $material)

                <tr class="border-t">
                    <td class="p-3">{{ $material->name }}</td>
                    <td class="text-center">{{ $material->department->department_name ?? '-' }}</td>
                    <td class="text-center">{{ $material->category->name ?? '-' }}</td>
                    <td class="text-center text-red-600 font-bold">{{ $material->quantity }}</td>
                </tr>

            @empty

                <tr>
                    <td colspan="4" class="text-center p-6">No out of stock materials.</td>
                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="bg-white rounded-lg shadow mt-8">

        <div class="border-b p-5">
            <h2 class="text-2xl font-bold">SECTION IV. Material Expiration</h2>
            <p class="text-gray-500 mt-1">Materials expiring within 30 days</p>
        </div>

        <table class="w-full">

            <thead class="bg-gray-100">
                <tr>
                    <th class="p-3 text-left">Material</th>
                    <th class="p-3">Department</th>
                    <th class="p-3">Batch No.</th>
                    <th class="p-3">Remaining</th>
                    <th class="p-3">Expiration Date</th>
                    <th class="p-3">Days Left</th>
                </tr>
            </thead>

            <tbody>

            @forelse($expiringMaterials as $batch)

                <tr class="border-t">
                    <td class="p-3">{{ $batch->material->name }}</td>
                    <td class="text-center">{{ $batch->material->department->department_name ?? '-' }}</td>
                    <td class="text-center">{{ $batch->batch_no }}</td>
                    <td class="text-center">{{ $batch->quantity_remaining }}</td>
                    <td class="text-center">{{ \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') }}</td>
                    <td class="text-center text-purple-700 font-bold">{{ now()->diffInDays($batch->expiration_date) }} days</td>
                </tr>

            @empty

                <tr>
                    <td colspan="6" class="text-center p-6">No materials expiring within 30 days.</td>
                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="bg-white rounded-lg shadow mt-8">

        <div class="border-b p-5">
            <h2 class="text-2xl font-bold">SECTION V. Expired Inventory Batches</h2>
            <p class="text-gray-500 mt-1">Restock batches past their expiration date.</p>
        </div>

        <table class="w-full">

            <thead class="bg-gray-100">
                <tr>
                    <th class="p-3 text-left">Material</th>
                    <th class="p-3">Department</th>
                    <th class="p-3">Batch No.</th>
                    <th class="p-3">Remaining</th>
                    <th class="p-3">Expiration Date</th>
                    <th class="p-3">Days Expired</th>
                </tr>
            </thead>

            <tbody>

            @forelse($expiredMaterials as $batch)

                <tr class="border-t">
                    <td class="p-3">{{ $batch->material->name }}</td>
                    <td class="text-center">{{ $batch->material->department->department_name ?? '-' }}</td>
                    <td class="text-center">{{ $batch->batch_no }}</td>
                    <td class="text-center">{{ $batch->quantity_remaining }}</td>
                    <td class="text-center">{{ \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') }}</td>
                    <td class="text-center text-red-600 font-bold">{{ \Carbon\Carbon::parse($batch->expiration_date)->diffInDays(now()) }} days</td>
                </tr>

            @empty

                <tr>
                    <td colspan="6" class="text-center p-6">No expired inventory batches.</td>
                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="bg-white rounded-lg shadow mt-8">

        <div class="border-b p-5">
            <h2 class="text-2xl font-bold">SECTION VI. Department Inventory Summary</h2>

            <p class="text-gray-500 mt-1">Aggregate materials released to each department.</p>
        </div>

        <table class="w-full">

            <thead class="bg-gray-100">
                <tr>
                    <th class="p-3 text-left">Department</th>
                    <th class="p-3">Materials</th>
                    <th class="p-3">Total Quantity</th>
                    <th class="p-3">Last Release</th>
                </tr>
            </thead>

            <tbody>

            @foreach($departmentSummary as $department)

                <tr class="border-t">
                    <td class="p-3">{{ $department->department_name }}</td>
                    <td class="text-center">{{ $department->total_materials }}</td>
                    <td class="text-center">{{ number_format($department->total_quantity) }}</td>
                    <td class="text-center">
                        {{ $department->last_release
                            ? \Carbon\Carbon::parse($department->last_release)->format('M d, Y')
                            : '-' }}
                    </td>
                </tr>

            @endforeach

            </tbody>

        </table>

    </div>

    <div class="bg-white rounded-lg shadow mt-8">

        <div class="border-b p-5">
            <h2 class="text-2xl font-bold">SECTION VII. Complete Inventory Listing</h2>
            <p class="text-gray-500 mt-1">All {{ $allMaterials->count() }} materials on record.</p>
        </div>

        <table class="w-full">

            <thead class="bg-gray-100">
                <tr>
                    <th class="p-3 text-left">Material</th>
                    <th class="p-3">Category</th>
                    <th class="p-3">Department</th>
                    <th class="p-3">Unit</th>
                    <th class="p-3">Quantity</th>
                    <th class="p-3">Threshold</th>
                    <th class="p-3">Status</th>
                </tr>
            </thead>

            <tbody>

            @php
                $statusBadges = [
                    'out_of_stock' => ['Out of Stock', 'bg-black'],
                    'critical' => ['Critical', 'bg-red-600'],
                    'low' => ['Low Stock', 'bg-yellow-500'],
                    'available' => ['Available', 'bg-green-600'],
                ];
            @endphp

            @forelse($allMaterials as $material)

                <tr class="border-t">
                    <td class="p-3">{{ $material->name }}</td>
                    <td class="text-center">{{ $material->category->name ?? '-' }}</td>
                    <td class="text-center">{{ $material->department->department_name ?? '-' }}</td>
                    <td class="text-center">{{ $material->unit->name ?? '-' }}</td>
                    <td class="text-center font-bold">{{ $material->quantity }}</td>
                    <td class="text-center">{{ $material->threshold }}</td>
                    <td class="text-center">
                        <span class="{{ $statusBadges[$material->stock_status][1] }} text-white px-3 py-1 rounded-full text-xs">
                            {{ $statusBadges[$material->stock_status][0] }}
                        </span>
                    </td>
                </tr>

            @empty

                <tr>
                    <td colspan="7" class="text-center p-6">No materials found.</td>
                </tr>

            @endforelse

            </tbody>

        </table>

    </div>

    <div class="bg-white rounded-lg shadow mt-8">

        <div class="border-b p-5">
            <h2 class="text-2xl font-bold">SECTION VIII. Department Inventory Breakdown</h2>
            <p class="text-gray-500 mt-1">Materials currently held per department.</p>
        </div>

        <div class="p-5 space-y-8">

        @foreach($materialsByDepartment as $departmentName => $departmentMaterials)

            <div>

                <h3 class="font-bold text-gray-800 mb-2">
                    {{ $departmentName }}
                    <span class="text-sm font-normal text-gray-500">
                        ({{ $departmentMaterials->count() }} materials)
                    </span>
                </h3>

                <table class="w-full">

                    <thead class="bg-gray-100">
                        <tr>
                            <th class="p-3 text-left">Material</th>
                            <th class="p-3">Category</th>
                            <th class="p-3">Unit</th>
                            <th class="p-3">Quantity</th>
                            <th class="p-3">Threshold</th>
                            <th class="p-3">Status</th>
                        </tr>
                    </thead>

                    <tbody>

                    @foreach($departmentMaterials as $material)

                        <tr class="border-t">
                            <td class="p-3">{{ $material->name }}</td>
                            <td class="text-center">{{ $material->category->name ?? '-' }}</td>
                            <td class="text-center">{{ $material->unit->name ?? '-' }}</td>
                            <td class="text-center font-bold">{{ $material->quantity }}</td>
                            <td class="text-center">{{ $material->threshold }}</td>
                            <td class="text-center">
                                <span class="{{ $statusBadges[$material->stock_status][1] }} text-white px-3 py-1 rounded-full text-xs">
                                    {{ $statusBadges[$material->stock_status][0] }}
                                </span>
                            </td>
                        </tr>

                    @endforeach

                    </tbody>

                </table>

            </div>

        @endforeach

        </div>

    </div>

    <!-- ===============================
    REPORT SIGNATURES
    =============================== -->

    <div class="bg-white rounded-lg shadow mt-8 p-8">

        <div class="grid grid-cols-3 gap-12 text-center">

            <div>

                <p class="mb-12 font-semibold">
                    Prepared By:
                </p>

                <div class="border-t border-black pt-2">

                    <strong>{{ auth()->user()->username }}</strong><br>

                    <span class="text-sm">
                        Inventory Supervisor
                    </span>

                </div>

            </div>

            <div>

                <p class="mb-12 font-semibold">
                    Checked By:
                </p>

                <div class="border-t border-black pt-2">

                    <strong>____________________</strong><br>

                    <span class="text-sm">
                        General Services Head
                    </span>

                </div>

            </div>

            <div>

                <p class="mb-12 font-semibold">
                    Approved By:
                </p>

                <div class="border-t border-black pt-2">

                    <strong>____________________</strong><br>

                    <span class="text-sm">
                        Campus Administrator
                    </span>

                </div>

            </div>

        </div>

    </div>

</div>

@endsection