<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Low Stock Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .text-right{

            text-align:right;

        }

        .header-table td{

            border:none;

        }

        .no-border{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>

Republic of the Philippines

</div>

<h2>

CAVITE STATE UNIVERSITY

</h2>

<div>

Carmona Campus

</div>

<h4>

GENERAL SERVICES OFFICE

</h4>

</td>

<td width="90">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

LOW STOCK REPORT

</h2>

<p class="text-center">

Materials Approaching Their Reorder Threshold

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

LSR-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

This report identifies inventory materials that have dropped
below their reorder threshold and should be scheduled for
procurement before reaching critical levels.

</p>

<table>

<tr>

<th>Total Low Stock Items</th>

<th>Low Stock Percentage</th>

<th>Departments Affected</th>

</tr>

<tr>

<td class="text-center">

{{ $lowStockCount }}

</td>

<td class="text-center">

{{ number_format($lowStockPercentage,2) }}%

</td>

<td class="text-center">

{{ $departmentsAffected }}

</td>

</tr>

</table>

<h3 class="section">

Detailed Low Stock Inventory

</h3>

<table>

<thead>

<tr>

<th width="40">

#

</th>

<th>

Material

</th>

<th>

Department

</th>

<th>

Category

</th>

<th>

Quantity

</th>

<th>

Threshold

</th>

<th>

Recommendation

</th>

</tr>

</thead>

<tbody>

@forelse($lowStockMaterials as $material)

<tr>

<td class="text-center">

{{ $loop->iteration }}

</td>

<td>

{{ $material->name }}

</td>

<td>

{{ $material->department->department_name ?? '-' }}

</td>

<td>

{{ $material->category->name ?? '-' }}

</td>

<td class="text-center">

{{ $material->quantity }}

</td>

<td class="text-center">

{{ $material->threshold }}

</td>

<td>

Schedule Procurement

</td>

</tr>

@empty

<tr>

<td colspan="7" class="text-center">

No low stock materials found.

</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

Procurement should be scheduled for all materials listed in this report before they drop into critical range. Departments should continuously monitor inventory levels and review reorder thresholds to prevent stock depletion.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
