<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Non-Movable Items Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>

Republic of the Philippines

</div>

<h2>

CAVITE STATE UNIVERSITY

</h2>

<div>

Carmona Campus

</div>

<h4>

GENERAL SERVICES OFFICE

</h4>

</td>

<td width="90">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

NON-MOVABLE ITEMS REPORT

</h2>

<p class="text-center">

Materials With No Request or Issuance Activity

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

NMV-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

This report identifies {{ $nonMovableCount }} materials
({{ number_format($nonMovablePercentage,2) }}% of the catalog) across
{{ $departmentsAffected }} department(s) that have never been issued
through a Material Request or Walk-In Issuance.

</p>

<table>

<tr>

<th>Non-Movable Items</th>

<th>Percentage of Inventory</th>

<th>Departments Affected</th>

</tr>

<tr>

<td class="text-center">

{{ $nonMovableCount }}

</td>

<td class="text-center">

{{ number_format($nonMovablePercentage,2) }}%

</td>

<td class="text-center">

{{ $departmentsAffected }}

</td>

</tr>

</table>

<h3 class="section">

Materials With No Request Activity

</h3>

<table>

<thead>

<tr>

<th width="40">

#

</th>

<th>

Material

</th>

<th>

Department

</th>

<th>

Category

</th>

<th>

Current Stock

</th>

<th>

Date Added

</th>

</tr>

</thead>

<tbody>

@forelse($nonMovable as $material)

<tr>

<td class="text-center">

{{ $loop->iteration }}

</td>

<td>

{{ $material->name }}

</td>

<td>

{{ $material->department->department_name ?? '-' }}

</td>

<td>

{{ $material->category->name ?? '-' }}

</td>

<td class="text-center">

{{ $material->quantity }}

</td>

<td class="text-center">

{{ $material->created_at->format('M d, Y') }}

</td>

</tr>

@empty

<tr>

<td colspan="6" class="text-center">

Every material has some request activity on record.

</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

Review whether these materials are still needed before including them
in the next procurement plan. Consider reassigning unused stock to a
department that could actually use it, instead of buying more
elsewhere.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
