<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Purchase Recommendations
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>

Republic of the Philippines

</div>

<h2>

CAVITE STATE UNIVERSITY

</h2>

<div>

Carmona Campus

</div>

<h4>

GENERAL SERVICES OFFICE

</h4>

</td>

<td width="90">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

PURCHASE RECOMMENDATIONS

</h2>

<p class="text-center">

What to Buy, What's Expiring, What's In Demand, and What's Unused

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

PUR-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Section I. Items to Purchase (Low / Critical / Out of Stock)

</h3>

<table>

<thead>

<tr>
<th>Material</th>
<th>Department</th>
<th>Category</th>
<th>Qty</th>
<th>Threshold</th>
<th>Status</th>
</tr>

</thead>

<tbody>

@php
    $statusLabels = [
        'out_of_stock' => 'Out of Stock',
        'critical' => 'Critical',
        'low' => 'Low Stock',
    ];
@endphp

@forelse($needsPurchase as $material)

<tr>
<td>{{ $material->name }}</td>
<td class="text-center">{{ $material->department->department_name ?? '-' }}</td>
<td class="text-center">{{ $material->category->name ?? '-' }}</td>
<td class="text-center">{{ $material->quantity }}</td>
<td class="text-center">{{ $material->threshold }}</td>
<td class="text-center">{{ $statusLabels[$material->stock_status] ?? $material->stock_status }}</td>
</tr>

@empty

<tr>
<td colspan="6" class="text-center">Nothing needs purchasing right now.</td>
</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Section II. Possible Expiration — {{ $monthLabel }}

</h3>

<table>

<thead>

<tr>
<th>Material</th>
<th>Department</th>
<th>Batch No.</th>
<th>Remaining</th>
<th>Expiration Date</th>
</tr>

</thead>

<tbody>

@forelse($expiringThisMonth as $batch)

<tr>
<td>{{ $batch->material->name ?? '-' }}</td>
<td class="text-center">{{ $batch->material->department->department_name ?? '-' }}</td>
<td class="text-center">{{ $batch->batch_no }}</td>
<td class="text-center">{{ $batch->quantity_remaining }}</td>
<td class="text-center">{{ \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') }}</td>
</tr>

@empty

<tr>
<td colspan="5" class="text-center">No batches expiring in {{ $monthLabel }}.</td>
</tr>

@endforelse

</tbody>

</table>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
