@extends('layouts.app')

@section('content')

<div class="bg-white rounded-xl shadow-lg p-6 lg:p-8">

    <!-- Header -->
    <div class="flex justify-between items-start mb-6">

        <div>

            <h2 class="text-3xl lg:text-4xl font-bold text-gray-800 flex items-center gap-3">
                🛒 Purchase Recommendations
            </h2>

            <p class="text-gray-500 text-lg mt-2 max-w-4xl leading-relaxed">
                What to buy right now — low, critical, and out of stock materials,
                plus anything about to expire this month.
            </p>

            <div class="mt-6 border border-gray-200 rounded-xl p-5 bg-gray-50">

                <div class="grid grid-cols-2 gap-4 text-base text-gray-700">

                    <div>
                        <span class="font-semibold">Report No.</span>
                        <p class="mt-1">PUR-{{ now()->format('YmdHis') }}</p>
                    </div>

                    <div>
                        <span class="font-semibold">Office</span>
                        <p class="mt-1">General Services Office</p>
                    </div>

                    <div>
                        <span class="font-semibold">Generated Date</span>
                        <p class="mt-1">{{ now()->format('F d, Y h:i A') }}</p>
                    </div>

                    <div>
                        <span class="font-semibold">Generated By</span>
                        <p class="mt-1">{{ auth()->user()->fullname ?? auth()->user()->name }}</p>
                    </div>

                </div>

            </div>

        </div>

        <div class="flex gap-2">

            <x-back-button :href="route('reports.inventory')" />

            <a
                href="{{ route('inventory.purchase-recommendations.print') }}"
                target="_blank"
                class="bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded">

                🖨 Print Official Report

            </a>

        </div>

    </div>

    <!-- KPI Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">

        <div class="bg-gradient-to-r from-red-600 to-red-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-red-100">Items to Purchase</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $needsPurchaseCount }}</h2>
                </div>
                <div class="text-5xl opacity-70">🛒</div>
            </div>
        </div>

        <div class="bg-gradient-to-r from-purple-600 to-purple-700 rounded-2xl shadow-lg text-white p-6">
            <div class="flex justify-between items-center">
                <div>
                    <p class="uppercase tracking-wider text-sm text-purple-100">Expiring in {{ $monthLabel }}</p>
                    <h2 class="text-5xl font-extrabold mt-3">{{ $expiringThisMonthCount }}</h2>
                </div>
                <div class="text-5xl opacity-70">⏳</div>
            </div>
        </div>

    </div>

    <!-- SECTION A: Items to Purchase -->
    <div class="border rounded-lg bg-gray-50 mb-6">

        <div class="border-b p-5">
            <h3 class="text-xl font-bold text-gray-800">
                🛒 Items to Purchase (Low / Critical / Out of Stock)
            </h3>
            <p class="text-gray-500 mt-1">
                Materials at or below their reorder threshold, most urgent first.
            </p>
        </div>

        <div class="overflow-x-auto">

            <table class="w-full">

                <thead class="bg-gray-100">
                    <tr>
                        <th class="p-3 text-left">Material</th>
                        <th class="p-3">Department</th>
                        <th class="p-3">Category</th>
                        <th class="p-3">Qty</th>
                        <th class="p-3">Threshold</th>
                        <th class="p-3">Status</th>
                    </tr>
                </thead>

                <tbody>

                @php
                    $statusBadges = [
                        'out_of_stock' => ['Out of Stock', 'bg-black'],
                        'critical' => ['Critical', 'bg-red-600'],
                        'low' => ['Low Stock', 'bg-yellow-500'],
                    ];
                @endphp

                @forelse($needsPurchase as $material)

                    <tr class="border-t bg-white">
                        <td class="p-3">{{ $material->name }}</td>
                        <td class="text-center">{{ $material->department->department_name ?? '-' }}</td>
                        <td class="text-center">{{ $material->category->name ?? '-' }}</td>
                        <td class="text-center font-bold">{{ $material->quantity }}</td>
                        <td class="text-center">{{ $material->threshold }}</td>
                        <td class="text-center">
                            <span class="{{ $statusBadges[$material->stock_status][1] }} text-white px-3 py-1 rounded-full text-xs">
                                {{ $statusBadges[$material->stock_status][0] }}
                            </span>
                        </td>
                    </tr>

                @empty

                    <tr>
                        <td colspan="6" class="text-center p-6 text-gray-500">
                            🎉 Nothing needs purchasing right now.
                        </td>
                    </tr>

                @endforelse

                </tbody>

            </table>

        </div>

    </div>

    <!-- SECTION B: Expiring This Month -->
    <div class="border rounded-lg bg-gray-50">

        <div class="border-b p-5">
            <h3 class="text-xl font-bold text-gray-800">
                ⏳ Possible Expiration — {{ $monthLabel }}
            </h3>
            <p class="text-gray-500 mt-1">
                Restock batches with an expiration date falling within this month.
            </p>
        </div>

        <div class="overflow-x-auto">

            <table class="w-full">

                <thead class="bg-gray-100">
                    <tr>
                        <th class="p-3 text-left">Material</th>
                        <th class="p-3">Department</th>
                        <th class="p-3">Batch No.</th>
                        <th class="p-3">Remaining</th>
                        <th class="p-3">Expiration Date</th>
                    </tr>
                </thead>

                <tbody>

                @forelse($expiringThisMonth as $batch)

                    <tr class="border-t bg-white">
                        <td class="p-3">{{ $batch->material->name ?? '-' }}</td>
                        <td class="text-center">{{ $batch->material->department->department_name ?? '-' }}</td>
                        <td class="text-center">{{ $batch->batch_no }}</td>
                        <td class="text-center">{{ $batch->quantity_remaining }}</td>
                        <td class="text-center {{ \Carbon\Carbon::parse($batch->expiration_date)->isPast() ? 'text-red-600 font-semibold' : '' }}">
                            {{ \Carbon\Carbon::parse($batch->expiration_date)->format('M d, Y') }}
                        </td>
                    </tr>

                @empty

                    <tr>
                        <td colspan="5" class="text-center p-6 text-gray-500">
                            No batches expiring in {{ $monthLabel }}.
                        </td>
                    </tr>

                @endforelse

                </tbody>

            </table>

        </div>

    </div>

</div>

@endsection
