<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>
        Budget Monitoring Report
    </title>

    <script>

        window.onload = function () {

            window.print();

        }

    </script>

    <style>

        body{

            font-family: Arial, Helvetica, sans-serif;
            font-size:12px;
            color:#000;
            margin:30px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th,
        td{

            border:1px solid #000;
            padding:6px;

        }

        th{

            background:#e5e7eb;

        }

        .text-center{

            text-align:center;

        }

        .header-table td{

            border:none;

        }

        h1,h2,h3,h4{

            margin:3px;

        }

        .section{

            margin-top:25px;

        }

        .signature td{

            border:none;
            padding-top:60px;

        }

        @page{

            size:A4 portrait;
            margin:12mm;

        }

    </style>

</head>

<body>

<table class="header-table">

<tr>

<td width="90">

<img
src="{{ asset('images/logo.png') }}"
width="80">

</td>

<td class="text-center">

<div>

Republic of the Philippines

</div>

<h2>

CAVITE STATE UNIVERSITY

</h2>

<div>

Carmona Campus

</div>

<h4>

GENERAL SERVICES OFFICE

</h4>

</td>

<td width="90">

</td>

</tr>

</table>

<hr>

<h2 class="text-center">

BUDGET MONITORING REPORT

</h2>

<p class="text-center">

Planning Year {{ $year }}

</p>

<table class="section">

<tr>

<td>

<strong>Report Number</strong>

</td>

<td>

BMR-{{ now()->format('YmdHis') }}

</td>

<td>

<strong>Generated Date</strong>

</td>

<td>

{{ now()->format('F d, Y h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Generated By</strong>

</td>

<td>

{{ auth()->user()->fullname ?? auth()->user()->name }}

</td>

<td>

<strong>Office</strong>

</td>

<td>

General Services Office

</td>

</tr>

</table>

<h3 class="section">

Executive Summary

</h3>

<p>

For planning year {{ $year }}, PPMPs across {{ $byDepartment->count() }} department(s) have allocated a total of ₱{{ number_format($totalAllocated, 2) }}, of which ₱{{ number_format($totalPlanned, 2) }} has been committed to planned line items, leaving ₱{{ number_format($totalRemaining, 2) }} remaining. ₱{{ number_format($totalApproved, 2) }} has been formally approved so far.

</p>

<table>

<tr>

<th>Total Allocated</th>

<th>Total Approved</th>

<th>Total Planned</th>

<th>Total Remaining</th>

</tr>

<tr>

<td class="text-center">₱{{ number_format($totalAllocated, 2) }}</td>

<td class="text-center">₱{{ number_format($totalApproved, 2) }}</td>

<td class="text-center">₱{{ number_format($totalPlanned, 2) }}</td>

<td class="text-center">₱{{ number_format($totalRemaining, 2) }}</td>

</tr>

</table>

<h3 class="section">

Budget Utilization by Department

</h3>

<table>

<thead>

<tr>

<th>Department</th>

<th>Plans</th>

<th>Allocated</th>

<th>Planned</th>

<th>Remaining</th>

<th>Utilization</th>

</tr>

</thead>

<tbody>

@forelse($byDepartment as $department => $row)

<tr>

<td>{{ $department }}</td>

<td class="text-center">{{ $row['plans_count'] }}</td>

<td class="text-center">₱{{ number_format($row['allocated'], 2) }}</td>

<td class="text-center">₱{{ number_format($row['planned'], 2) }}</td>

<td class="text-center">₱{{ number_format($row['remaining'], 2) }}</td>

<td class="text-center">{{ $row['utilization'] }}%</td>

</tr>

@empty

<tr>

<td colspan="6" class="text-center">No procurement plans found for {{ $year }}.</td>

</tr>

@endforelse

</tbody>

</table>

<h3 class="section">

Recommendation

</h3>

<p>

Departments above 90% utilization should review remaining line items before adding further commitments. Departments with low utilization relative to their allocation may have room to fund additional priority needs.

</p>

<table class="signature">

<tr>

<td class="text-center">

_________________________

<br>

Prepared By

</td>

<td class="text-center">

_________________________

<br>

Reviewed By

</td>

<td class="text-center">

_________________________

<br>

Approved By

</td>

</tr>

</table>

</body>

</html>
